services:
  next-buzz:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: next-buzz
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db-buzz
  db-buzz:
    image: postgres:14
    container_name: db-buzz
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-buzz
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: