services:
  next-buzz-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: next-buzz-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - db-buzz

  next-buzz-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: next-buzz-backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db-buzz
  db-buzz:
    image: postgres:14
    container_name: db-buzz
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-buzz
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: